# permissions for end users to view redisreplicas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: redisreplica-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: redis-operator
    app.kubernetes.io/part-of: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: redisreplica-viewer-role
rules:
- apiGroups:
  - redis.mysite.cn
  resources:
  - redisreplicas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redis.mysite.cn
  resources:
  - redisreplicas/status
  verbs:
  - get
